config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/shop'
  get 'pages/about'
  get 'pages/contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def shop
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dedwarseanjelier1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="container">
	<div class="row">
		<div class="logo">
			<h2>De Dwarse Anjelier</h2>
		</div>
	</div>
	<div class="banner">
		<img src="#" alt="">
	</div>
	<div class="row">
		<div class="footer">
			<ul>
				<%= link_to "HomePage", pages_about_path %> 
				<li><a href="#">HomePage</a></li>
				<li><a href="#">Privacy policy</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</div>
	</div>


</div>

app/views/pages/shop.html.erb
<h1>Pages#shop</h1>
<p>Find me in app/views/pages/shop.html.erb</p>